V.1.5.2: Added multiples features
simoneldevig/jira-toggl pull request #24
Opened 2021-05-28 12:15 UTC by unrealmitch

- Included option to avoid include issue ID in jira worklog description (see readme)
- Included option to split toggl description with some string (see readme)
- Included link / href in issue ID of popup
- Now, if search issue in description is enabled, first searh in description and THEN search in Project Title (before just in description)
- Search also Issue ID in Project Name (Toggl) as in description (before just take the Project Name)
- Navigation buttons (back / next day in calendar)
- Button to refresh and reset / go today)
- Now it shows actual "in progress" task of toggl as "WIP" in popup (before showed as "too short")
- Different format (red bold) for task in "WIP" or "too short"
- Fixed TOTAL sum (before showed "too short" or "WIP", where there are some task with this duration)
- Now TOTAL says "No entries" when fetch finish (before said all time "Loading")
- Other mini improvements

It's my first conntact with Vue, so don't blame me pls ^^

Also I edited default option "Parse Jira issue from description" (default: false, now: true)

2021-06-01 08:31 UTC, simoneldevig commented
@unrealmitch wow thanks for the huge PR!

I'll try to see if I can have a look at it in the weekend 😄

2021-06-07 05:29 UTC, simoneldevig commented on src/popup/App.vue
> +          //reject(log);  If don't find in description, search in project title
**Suggestion**
Just remove the ```reject(log)```and keep the comment

2021-06-07 06:03 UTC, simoneldevig requested changes
Good job @unrealmitch!

Code's looking good and there was only a minor suggestion. 

I only have some comments to the functional improvements 😄 

- Different format (red bold) for task in "WIP" or "too short"
  - Can you change the color to the default red? (--md-theme-default-accent)
- Navigation buttons (back / next day in calendar)
  - Can you remove the background so the date navigation buttons and align them to the icon in the datepicker?
- Button to refresh and reset / go today)
  - Could you move the refresh button to the top bar and make the reset button to just a text that is positioned absolute in the top right?
- Button to open Clockwork Free Jira Plugin (To show own worklogs between selected dates) and option to enable it
  - Great idea! But maybe instead of tying it to a specific JIRA plugin then it could just be a link that could be edited in the settings page? Then it could be a link to the worklog by default and people would be able to insert a link to Clockwork, Tempo Planner etc. according to the plugin they use for time registration? 

There is a lot of link errors which Travis CI fails. You can autofix these by running ```npx eslint --ext .js,.vue src --fix``` in the console.

All in all I really like the improvements and only have stuff for the UI 🚀  I hacked an example together in the inspector to show how I think the UI should look 😄 

<img width="699" alt="Screenshot 2021-06-07 at 07 56 38" src="https://user-images.githubusercontent.com/6176830/120966646-cd4e8980-c766-11eb-9527-f1be46324701.png">

2021-06-07 08:46 UTC, unrealmitch commented
> 
> 
> Good job @unrealmitch!
> 
> Code's looking good and there was only a minor suggestion.
> 
> I only have some comments to the functional improvements 😄
> 
>     * Different format (red bold) for task in "WIP" or "too short"
>       
>       * Can you change the color to the default red? (--md-theme-default-accent)
> 
>     * Navigation buttons (back / next day in calendar)
>       
>       * Can you remove the background so the date navigation buttons and align them to the icon in the datepicker?
> 
>     * Button to refresh and reset / go today)
>       
>       * Could you move the refresh button to the top bar and make the reset button to just a text that is positioned absolute in the top right?
> 
>     * Button to open Clockwork Free Jira Plugin (To show own worklogs between selected dates) and option to enable it
>       
>       * Great idea! But maybe instead of tying it to a specific JIRA plugin then it could just be a link that could be edited in the settings page? Then it could be a link to the worklog by default and people would be able to insert a link to Clockwork, Tempo Planner etc. according to the plugin they use for time registration?
> 
> 
> There is a lot of link errors which Travis CI fails. You can autofix these by running `npx eslint --ext .js,.vue src --fix` in the console.
> 
> All in all I really like the improvements and only have stuff for the UI 🚀 I hacked an example together in the inspector to show how I think the UI should look 😄
> 
> <img alt="Screenshot 2021-06-07 at 07 56 38" width="699" src="https://user-images.githubusercontent.com/6176830/120966646-cd4e8980-c766-11eb-9527-f1be46324701.png">

Wow, graeat suggestions, the UI looks amazing! I will try to implement all this weekend!

2021-06-13 17:13 UTC, unrealmitch commented
I've had some free time to apply the UI changes that you described! Now it looks much better, thanks.

I've also fixed a couple of things, although Travis doesn't seem to like me, despite running said command on my PC with no problems :(

2021-06-21 06:19 UTC, simoneldevig requested changes
@unrealmitch just tested it out and looks pretty good, and nice feature with the date persistence 💯 

Could you maybe fix the following.

1. Fix the date and text alignment: 
![Screenshot 2021-06-21 at 08 15 36](https://user-images.githubusercontent.com/6176830/122715286-eed06a80-d268-11eb-9e2c-052a0ad565c6.png)
2. Make all the options false by default
![Screenshot 2021-06-21 at 08 16 48](https://user-images.githubusercontent.com/6176830/122715359-09a2df00-d269-11eb-9f60-90fccfbcab8e.png)
3. Remove the clockwork path by default and maybe remove the (Usually Clockwork Free) text from the checkbox so it's not tied to anything.
4. Move the Save Settings button to the bottom of the settings page instead of being in the middle 

Once the requested changes are fixed I will merge and release 👍

2021-06-21 06:20 UTC, simoneldevig commented on src/options/App.vue
> +          <!-- <br><label>Start weekday:</label>
@unrealmitch properly should remove the unused code

2021-06-21 15:57 UTC, unrealmitch commented
Solved 2,3 and 4. But I didn't understand point 1 "Fix the date and text alignment". I keep de format of calendar of original plugin. Did you mean change alignment to center?

2021-06-21 16:04 UTC, unrealmitch commented
I also added the option to start week on monday (Calendar Picker), as it was mentioned in  #21, and with the option to save dates #20, all issues would be closed (and with button of reset dates it will works well)

2021-06-21 17:45 UTC, simoneldevig commented
@unrealmitch 1 is just the vertical alignment between label and value on the date input :-)

2021-06-22 08:47 UTC, unrealmitch commented
In this way? Updated css in last commit.

![image](https://user-images.githubusercontent.com/5290755/122894115-362d2880-d347-11eb-9a00-4e17a0bf6da5.png)

2021-06-22 09:03 UTC, unrealmitch commented
In this way? Updated css in last commit.

![image](https://user-images.githubusercontent.com/5290755/122896429-5bbb3180-d349-11eb-8e12-416379818ba7.png)

2021-06-22 09:25 UTC, merged